// Stamps the build with a version so the running app can notice a newer one.
import { writeFileSync, mkdirSync } from 'node:fs'
import { execSync } from 'node:child_process'
let sha = 'dev'
try { sha = execSync('git rev-parse --short HEAD').toString().trim() } catch { /* not a git checkout */ }
const version = `${sha}-${Date.now()}`
mkdirSync('public', { recursive: true })
writeFileSync('public/version.json', JSON.stringify({ version }) + '\n')
writeFileSync('src/version.ts', `// generated by scripts/write-version.mjs at build time\nexport const BUILD_VERSION = '${version}'\n`)
console.log('version', version)
